//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatalogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CatalogResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;What is &quot;Catalog Yottos&quot;?&lt;/b&gt;&lt;br /&gt;&lt;br /&gt; &quot;Catalog Yottos&quot; is a catalog of Internet sites. Sites in the catalog are divided by thematic categories so that search of a necessary site was as much as possible simple. Sites are placed in decreasing order their popularity among Yottos users.&lt;br /&gt;&lt;br /&gt;&lt;b&gt;What for &quot;Catalog Yottos&quot; is necessary?&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;If The site of certain subjects there is no necessity to search for it is necessary for you, using search engines and rummaging set of poor-quality site [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutCatalogDescription_0 {
            get {
                return ResourceManager.GetString("AboutCatalogDescription_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions or offers under the maintenance and the form of representation of the information,.
        /// </summary>
        internal static string AboutCatalogDescription_1 {
            get {
                return ResourceManager.GetString("AboutCatalogDescription_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The administration will be grateful for any comments and recommendations rather Yottos..
        /// </summary>
        internal static string AboutCatalogDescription_2 {
            get {
                return ResourceManager.GetString("AboutCatalogDescription_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Yottos.
        /// </summary>
        internal static string AboutLinkCaption {
            get {
                return ResourceManager.GetString("AboutLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add site.
        /// </summary>
        internal static string AddSiteLinkCaption {
            get {
                return ResourceManager.GetString("AddSiteLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisment programms.
        /// </summary>
        internal static string AdvertLinkCaption {
            get {
                return ResourceManager.GetString("AdvertLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string CatalogAddAbout {
            get {
                return ResourceManager.GetString("CatalogAddAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatalogAddAboutDescr_default.
        /// </summary>
        internal static string CatalogAddAboutDescr {
            get {
                return ResourceManager.GetString("CatalogAddAboutDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter site&apos;s description!.
        /// </summary>
        internal static string CatalogAddAboutRequired {
            get {
                return ResourceManager.GetString("CatalogAddAboutRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong security code from automatic registrations specified!.
        /// </summary>
        internal static string CatalogAddAutoCustom {
            get {
                return ResourceManager.GetString("CatalogAddAutoCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add site.
        /// </summary>
        internal static string CatalogAddButtonText {
            get {
                return ResourceManager.GetString("CatalogAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail:.
        /// </summary>
        internal static string CatalogAddEmail {
            get {
                return ResourceManager.GetString("CatalogAddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong e-mail!.
        /// </summary>
        internal static string CatalogAddEmailRegular {
            get {
                return ResourceManager.GetString("CatalogAddEmailRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail!.
        /// </summary>
        internal static string CatalogAddEmailRequired {
            get {
                return ResourceManager.GetString("CatalogAddEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add it to the catalog.
        /// </summary>
        internal static string CatalogAddLinkCaption {
            get {
                return ResourceManager.GetString("CatalogAddLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatalogAddNameDescr_default.
        /// </summary>
        internal static string CatalogAddNameDescr {
            get {
                return ResourceManager.GetString("CatalogAddNameDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number, displayed on the picture, and click button &apos;Add site&apos;.
        /// </summary>
        internal static string CatalogAddSecretWord {
            get {
                return ResourceManager.GetString("CatalogAddSecretWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select catalog chapter:.
        /// </summary>
        internal static string CatalogAddSelectRootCategory {
            get {
                return ResourceManager.GetString("CatalogAddSelectRootCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select sub category:.
        /// </summary>
        internal static string CatalogAddSelectSubCategory {
            get {
                return ResourceManager.GetString("CatalogAddSelectSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string CatalogAddSiteName {
            get {
                return ResourceManager.GetString("CatalogAddSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site address:.
        /// </summary>
        internal static string CatalogAddSiteUrl {
            get {
                return ResourceManager.GetString("CatalogAddSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your site will be published in Catalog, if:.
        /// </summary>
        internal static string CatalogAddTitle {
            get {
                return ResourceManager.GetString("CatalogAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;It&apos;s maintenance does not contradict the legislation (does not propagandise violence, racial hatred, a pornography, corruption and so forth); &lt;/li&gt;&lt;li&gt; the site or its basic sections are not in development;&lt;/li&gt;&lt;li&gt; The site subjects answer the declared heading;&lt;/li&gt;&lt;li&gt;Your site is not &lt;i&gt;a mirror&lt;/i&gt; of other site.&lt;/li&gt;.
        /// </summary>
        internal static string CatalogAddTitleDescr_0 {
            get {
                return ResourceManager.GetString("CatalogAddTitleDescr_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yottos reserves the right to itself to reject inquiry about site registration in the catalog without explanations.  &lt;br /&gt;  &lt;br /&gt;  All fields are obligatory to filling!.
        /// </summary>
        internal static string CatalogAddTitleDescr_1 {
            get {
                return ResourceManager.GetString("CatalogAddTitleDescr_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter site&apos;s name!.
        /// </summary>
        internal static string CatalogAddTitleRequired {
            get {
                return ResourceManager.GetString("CatalogAddTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: http://yottos.com/.
        /// </summary>
        internal static string CatalogAddURLDescr {
            get {
                return ResourceManager.GetString("CatalogAddURLDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong site address!.
        /// </summary>
        internal static string CatalogAddURLRegular {
            get {
                return ResourceManager.GetString("CatalogAddURLRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter site address!.
        /// </summary>
        internal static string CatalogAddURLRequired {
            get {
                return ResourceManager.GetString("CatalogAddURLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string CatalogLinkCaption {
            get {
                return ResourceManager.GetString("CatalogLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add one more site.
        /// </summary>
        internal static string CatalogLinkPostedAddMore {
            get {
                return ResourceManager.GetString("CatalogLinkPostedAddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to catalog.
        /// </summary>
        internal static string CatalogLinkPostedBackToCatalog {
            get {
                return ResourceManager.GetString("CatalogLinkPostedBackToCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inquiry about addition of your site in catalog Yottos is sent and will be considered in the near future..
        /// </summary>
        internal static string CatalogLinkPostedResult {
            get {
                return ResourceManager.GetString("CatalogLinkPostedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        internal static string CatalogLinkPotedBaners {
            get {
                return ResourceManager.GetString("CatalogLinkPotedBaners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding of baner on any project by the robot increases the meaningfulness of the page, depending of it&apos;s size..
        /// </summary>
        internal static string CatalogLinkPotedBanersInfo {
            get {
                return ResourceManager.GetString("CatalogLinkPotedBanersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you very much, for participation in forming given project!&lt;br/&gt;Also, we wold thankful if you place a baner to your site on any of the Yottos projects. Baners could be found.
        /// </summary>
        internal static string CatalogLinkPotedText {
            get {
                return ResourceManager.GetString("CatalogLinkPotedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        internal static string CatalogTitle {
            get {
                return ResourceManager.GetString("CatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string CategoryLabelText {
            get {
                return ResourceManager.GetString("CategoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        internal static string ContactLinkCaption {
            get {
                return ResourceManager.GetString("ContactLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitLinkCaption {
            get {
                return ResourceManager.GetString("ExitLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Image/Logos/en-US.gif.
        /// </summary>
        internal static string LogoUrl {
            get {
                return ResourceManager.GetString("LogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPage.
        /// </summary>
        internal static string MainPageLinkCaption {
            get {
                return ResourceManager.GetString("MainPageLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rynok.
        /// </summary>
        internal static string MarketLinkCaption {
            get {
                return ResourceManager.GetString("MarketLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://yottos.com/About/AboutYottos.aspx.
        /// </summary>
        internal static string Master_AboutYottos {
            get {
                return ResourceManager.GetString("Master_AboutYottos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://adload.yottos.com/.
        /// </summary>
        internal static string Master_AdloadLink {
            get {
                return ResourceManager.GetString("Master_AdloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://news.yottos.com/.
        /// </summary>
        internal static string Master_NewsLink {
            get {
                return ResourceManager.GetString("Master_NewsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.yottos.com/PersonalRoom/Default.aspx.
        /// </summary>
        internal static string Master_PersonalLink {
            get {
                return ResourceManager.GetString("Master_PersonalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://rynok.yottos.com/.
        /// </summary>
        internal static string Master_RynokLink {
            get {
                return ResourceManager.GetString("Master_RynokLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.yottos.com/.
        /// </summary>
        internal static string Master_WebLink {
            get {
                return ResourceManager.GetString("Master_WebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsLinkCaption {
            get {
                return ResourceManager.GetString("NewsLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter to the Personal room.
        /// </summary>
        internal static string PersonalLinkCaption {
            get {
                return ResourceManager.GetString("PersonalLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take part in teaching of intellectual search of Yottos.
        /// </summary>
        internal static string QuestionnaireLinkCaption {
            get {
                return ResourceManager.GetString("QuestionnaireLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer:.
        /// </summary>
        internal static string QuestionResultAnswer {
            get {
                return ResourceManager.GetString("QuestionResultAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to the reliable detailed information of answer:.
        /// </summary>
        internal static string QuestionResultAnswerLink {
            get {
                return ResourceManager.GetString("QuestionResultAnswerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answers for the question put by you:.
        /// </summary>
        internal static string QuestionResultAnswers {
            get {
                return ResourceManager.GetString("QuestionResultAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string QuestionResultEdit {
            get {
                return ResourceManager.GetString("QuestionResultEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on this reference Your questioning will be always, you can save it. also by your wish you can lay out it there where will count up necessary..
        /// </summary>
        internal static string QuestionResultMessage {
            get {
                return ResourceManager.GetString("QuestionResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save questionnaire.
        /// </summary>
        internal static string QuestionResultSave {
            get {
                return ResourceManager.GetString("QuestionResultSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yet are there associations ?.
        /// </summary>
        internal static string QuestionsAddAnswer {
            get {
                return ResourceManager.GetString("QuestionsAddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer which associative comes the first in your head on a put a question by you:.
        /// </summary>
        internal static string QuestionsAnswerCaption_1 {
            get {
                return ResourceManager.GetString("QuestionsAnswerCaption_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer which associative comes the second in your head on a put a question by you:.
        /// </summary>
        internal static string QuestionsAnswerCaption_2 {
            get {
                return ResourceManager.GetString("QuestionsAnswerCaption_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer which associative comes the third in your head on a put a question by you:.
        /// </summary>
        internal static string QuestionsAnswerCaption_3 {
            get {
                return ResourceManager.GetString("QuestionsAnswerCaption_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer which associative comes the fourth in your head on a put a question by you:.
        /// </summary>
        internal static string QuestionsAnswerCaption_4 {
            get {
                return ResourceManager.GetString("QuestionsAnswerCaption_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer which associative comes the fifth in your head on a put a question by you:.
        /// </summary>
        internal static string QuestionsAnswerCaption_5 {
            get {
                return ResourceManager.GetString("QuestionsAnswerCaption_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right answer which associative comes the sixth in your head on a put a question by you:.
        /// </summary>
        internal static string QuestionsAnswerCaption_6 {
            get {
                return ResourceManager.GetString("QuestionsAnswerCaption_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill the field!.
        /// </summary>
        internal static string QuestionsAnswerErrorMessage {
            get {
                return ResourceManager.GetString("QuestionsAnswerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associative photo of this answer:.
        /// </summary>
        internal static string QuestionsAnswerImageCaption {
            get {
                return ResourceManager.GetString("QuestionsAnswerImageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can specify reference to the reliable detailed information about the first answer:.
        /// </summary>
        internal static string QuestionsAnswerLinkCaption {
            get {
                return ResourceManager.GetString("QuestionsAnswerLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all of the fields as far as your knowledges..
        /// </summary>
        internal static string QuestionsFill {
            get {
                return ResourceManager.GetString("QuestionsFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish questioning.
        /// </summary>
        internal static string QuestionsFinish {
            get {
                return ResourceManager.GetString("QuestionsFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give answers for the question put by you:.
        /// </summary>
        internal static string QuestionsGiveAnswers {
            get {
                return ResourceManager.GetString("QuestionsGiveAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write short accessible human language not tie down to the keywords!.
        /// </summary>
        internal static string QuestionsGiveAnswersHint {
            get {
                return ResourceManager.GetString("QuestionsGiveAnswersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a searching question on which you know an answer.
        /// </summary>
        internal static string QuestionsGiveQuestion {
            get {
                return ResourceManager.GetString("QuestionsGiveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program of teaching of the system of understanding of human language.&lt;br /&gt;
        ///Purpose of questionnaire - to set any questions and get on them answers by an accessible human language..
        /// </summary>
        internal static string QuestionsMainTitle {
            get {
                return ResourceManager.GetString("QuestionsMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are the owner of resources on which you put Refs.s, we&apos;ll be thankful if you&apos;ll put a backlink on this page, for bringing in of people understandings this area which can set more various questions and give answers on them..
        /// </summary>
        internal static string QuestionsOwnerHint {
            get {
                return ResourceManager.GetString("QuestionsOwnerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yottos | questioning.
        /// </summary>
        internal static string QuestionsPageTitle {
            get {
                return ResourceManager.GetString("QuestionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What area are you a professional in or simply have experience?.
        /// </summary>
        internal static string QuestionsProfession {
            get {
                return ResourceManager.GetString("QuestionsProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;all categories&gt;&gt;.
        /// </summary>
        internal static string RootAllCategoriesText {
            get {
                return ResourceManager.GetString("RootAllCategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Catalog.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string SearchNoResultInternet {
            get {
                return ResourceManager.GetString("SearchNoResultInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;By your inquiry no results found.&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;Recommendations:&lt;ul&gt;&lt;li&gt;Check up spelling of words.&lt;/li&gt;&lt;li&gt;Try other keywords.&lt;/li&gt;&lt;li&gt;Try: to search &apos;#&apos; in the &apos;$&apos;&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using this form you can set up the results page in catalog.
        /// </summary>
        internal static string SettingsDescriptionCaption {
            get {
                return ResourceManager.GetString("SettingsDescriptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface language:.
        /// </summary>
        internal static string SettingsLanguageCaption {
            get {
                return ResourceManager.GetString("SettingsLanguageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsLinkCaption {
            get {
                return ResourceManager.GetString("SettingsLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results per page..
        /// </summary>
        internal static string SettingsOnThePageCaption {
            get {
                return ResourceManager.GetString("SettingsOnThePageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display: .
        /// </summary>
        internal static string SettingsPageSizeCaption {
            get {
                return ResourceManager.GetString("SettingsPageSizeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings and return to the catalog..
        /// </summary>
        internal static string SettingsSaveAndReturnCaption {
            get {
                return ResourceManager.GetString("SettingsSaveAndReturnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string SettingsSaveButtonCaption {
            get {
                return ResourceManager.GetString("SettingsSaveButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yottos | settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common settings.
        /// </summary>
        internal static string SettingsTitleCaption {
            get {
                return ResourceManager.GetString("SettingsTitleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        internal static string SettingsTransferButtonCaption {
            get {
                return ResourceManager.GetString("SettingsTransferButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make as default page.
        /// </summary>
        internal static string StartLinkCaption {
            get {
                return ResourceManager.GetString("StartLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string TaskLinkCaption {
            get {
                return ResourceManager.GetString("TaskLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page: Catalog.
        /// </summary>
        internal static string ToCatalogListLinkCaption {
            get {
                return ResourceManager.GetString("ToCatalogListLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string WebLinkCaption {
            get {
                return ResourceManager.GetString("WebLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        internal static string ZeroLinkCaption {
            get {
                return ResourceManager.GetString("ZeroLinkCaption", resourceCulture);
            }
        }
    }
}
