#include "FrameTemplate.h"

/** Шаблон информера с тизерами со следующими подстановками (существовавший шаблон):

    %1%	    CSS
    %2%	    JSON для initads (предложения, которые должны показаться на первой
	    странице)
    %3%	    количество товаров на странице
    %4%	    ссылка на скрипт получения следующей порции предложений в json,
	    к ней будут добавляться дополнительные параметры.
*/
bool FrameTemplate::initFrameTemplate()
{
	if (frameTemplate!="")
	{
		return true;
	}

	frameTemplate = 
        "<!doctype html public '-//w3c//dtd xhtml 1.0 strict//en' 'http://www.w3.org/tr/xhtml1/dtd/xhtml1-strict.dtd'>\n"
        "<html xmlns='http://www.w3.org/1999/xhtml' style='height: 100%%;'>\n"
        "    <head>\n"
        "        <meta http-equiv='content-type' content='text/html; charset=utf-8' />\n"
        "    </head>\n"
        "    <body style='margin:0 auto; display:table; height:100%%;'>\n"
        "       <div id='content'></div>\n"
		"       <script type='text/javascript' language='JavaScript'> \n"
        "            var userId = '';"
        "            var userIdLocalStore = null;"
        "            var userIdCookies = null;"
        "            var userIdFlashCookies = null;"
        "            var userIdGlobalCookies = null;"
        "            var localStorageAvailable = false;"
        "            ;var query='%2%';"
        "            ;var rand = Math.floor(Math.random() * 1000000);"
        "            ;var iframe_id = 'yottos' + rand;"
        "            ;function iframe_query(){"
        "                var result = query;"
        "                result += '&uid=';"
        "                result += userId;"
        "                return result;"
        "            }"
        "            (function(){"
        "                'use strict';"
        "                var counter = 0;"
        "                window.SwfStore = function(config){"
        "                    config = config || {};"
        "                    var defaults = {"
        "                        swf_url: '/storage.swf',"
        "                        namespace: 'user_id',"
        "                        path: '/',"
        "                        onready: null,"
        "                        onerror: null"
        "                    };"
        "                    var key;"
        "                    for(key in defaults){"
        "                        if(defaults.hasOwnProperty(key)){"
        "                            if(!config.hasOwnProperty(key)){"
        "                                config[key] = defaults[key];"
        "                            }"
        "                        }"
        "                    }"
        "                    if(window.SwfStore[config.namespace]){"
        "                        throw \"There is already an instance of SwfStore using the '\" + config.namespace + \"' namespace. Use that instance or specify an alternate namespace in the config.\";"
        "                    }"
        "                    this.config = config;"
        "                    function id(){"
        "                        return 'SwfStore_' + config.namespace + '_' +  (counter++);"
        "                    }"
        "                    function div(){"
        "                        var d = document.createElement('div');"
        "                        document.body.appendChild(d);"
        "                        d.id = id();"
        "                        d.style.position = 'absolute';"
        "                        d.style.top = '-2000px';"
        "                        d.style.left = '-2000px';"
        "                        return d;"
        "                    }"
        "                    SwfStore[config.namespace] = this;"
        "                    var swfContainer = div();"
        "                    var swfName = id();"
        "                    var flashvars = 'logfn=SwfStore.' + config.namespace + '.log&amp;' + "
        "                        'onload=SwfStore.' + config.namespace + '.onload&amp;' +"
        "                        'onerror=SwfStore.' + config.namespace + '.onerror&amp;' + "
        "                        (config.path ? 'LSOPath=' + config.path + '&amp;' : '') +"
        "                        'LSOName=' + config.namespace;"
        "                    swfContainer.innerHTML = '<object height=\"100\" width=\"500\" codebase=\"https://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab\" id=\"' + "
        "                        swfName + '\" classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\">' +"
        "                        '	<param value=\"' + config.swf_url + '\" name=\"movie\">' + "
        "                        '	<param value=\"' + flashvars + '\" name=\"FlashVars\">' + "
        "                        '	<param value=\"always\" name=\"allowScriptAccess\">' + "
        "                        '	<embed height=\"375\" align=\"middle\" width=\"500\" pluginspage=\"https://www.macromedia.com/go/getflashplayer\" ' + "
        "                        'flashvars=\"' + flashvars + '\" type=\"application/x-shockwave-flash\" allowscriptaccess=\"always\" quality=\"high\" loop=\"false\" play=\"true\" ' + "
        "                        'name=\"' + swfName + '\" bgcolor=\"#ffffff\" src=\"' + config.swf_url + '\">' + "
        "                        '</object>';"
        "                    this.swf = document[swfName] || window[swfName];"
        "                    this._timeout = setTimeout(function(){"
        "                        config.onerror();"
        "                    }, 1000);"
        "                };"
        "                function checkData(data){"
        "                    if(typeof data === 'function'){"
        "                        throw 'SwfStore Error: Functions cannot be used as keys or values.';"
        "                    }"
        "                }"
        "                SwfStore.prototype = {"
        "                    version: '1.7',"
        "                    ready: false,"
        "                    set: function(key, value){"
        "                        this._checkReady();"
        "                        checkData(key);"
        "                        checkData(value);"
        "                        this.swf.set(key, value);"
        "                    },"
        "                    get: function(key){"
        "                        this._checkReady();"
        "                        checkData(key);"
        "                        return this.swf.get(key);"
        "                    },"
        "                    getAll: function(){"
        "                        this._checkReady();"
        "                        var data = this.swf.getAll();"
        "                        if(data.__flashBugFix){"
        "                            delete data.__flashBugFix;"
        "                        }"
        "                        return data;"
        "                    },"
        "                    clear: function(key){"
        "                        this._checkReady();"
        "                        checkData(key);"
        "                        this.swf.clear(key);"
        "                    },"
        "                    _checkReady: function(){"
        "                        if(!this.ready){"
        "                            throw '';"
        "                        }"
        "                    },"
        "                    'onload': function(){"
        "                        var that = this;"
        "                        setTimeout(function(){"
        "                          clearTimeout(that._timeout);"
        "                          that.ready = true;"
        "                          that.set('__flashBugFix','1');"
        "                          that.config.onready();"
        "                        }, 0);"
        "                    },"
        "                    onerror: function(){"
        "                        clearTimeout(this._timeout);"
        "                        this.config.onerror();"
        "                    }"
        "                };"
        "            }());"
        "            ;function isLocalStorageAvailable()"
        "            {"
        "                try {"
        "                return 'localStorage' in window && window['localStorage'] !== null;"
        "                } catch (e) {"
        "                    return false;"
        "                }"
        "            }"
        "            function set_cookie ( name, value, path, domain, secure )"
        "            {"
        "              var cookie_string = name + '=' + escape ( value );"
        "              var expires = new Date();"
        "              expires.setTime(expires.getTime()+(365*24*60*60*1000));"
        "              cookie_string += '; expires=' + expires.toGMTString();"
        "              cookie_string += '; path=' + escape ('/');"
        "              if ( domain )"
        "                    cookie_string += '; domain=' + escape ( domain );"
        "              document.cookie = cookie_string;"
        "            };"
        "            function get_cookie(cookie_name)"
        "            {"
        "              var results = document.cookie.match ( '(^|;) ?' + cookie_name + '=([^;]*)(;|$)' );"
        "               if ( results )"
        "                return ( unescape ( results[2] ) );"
        "              else"
        "                return null;"
        "            }"
        "            (function(){"
        "                var mySwfStore = new SwfStore({"
        "                    namespace: 'user_id',"
        "                    swf_url: 'http://cdn.yottos.com/storage.swf',"
        "                    onready: function(){"
        "                        userIdFlashCookies = mySwfStore.get('user_id');"
        "                        localStorageAvailable = isLocalStorageAvailable();"
        "                        userIdCookies = get_cookie('user_id');"
        "                        userIdGlobalCookies = get_cookie('user_id_global');"
        "                        if (localStorageAvailable)"
        "                        {"
        "                            userIdLocalStore = localStorage.getItem('user_id');"
        "                            if (userIdFlashCookies != null)"
        "                            {"
        "                                userId = userIdFlashCookies;"
        "                            }"
        "                            else if (userIdLocalStore != null && userIdCookies != null && userIdGlobalCookies != null && userIdFlashCookies == null)"
        "                            {"
        "                                if (userIdLocalStore == userIdCookies == userIdGlobalCookies)"
        "                                {"
        "                                    userId = userIdLocalStore;"
        "                                }"
        "                                else if (userIdLocalStore == userIdCookies != userIdGlobalCookies)"
        "                                {"
        "                                    userId = userIdGlobalCookies;"
        "                                }"
        "                                else"
        "                                {"
        "                                    userId = userIdGlobalCookies;"
        "                                }"
        "                            }"
        "                            else if (userIdLocalStore != null && userIdCookies == null && userIdGlobalCookies != null && userIdFlashCookies == null)"
        "                            {"
        "                                    userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdLocalStore == null && userIdCookies != null && userIdGlobalCookies != null && userIdFlashCookies == null)"
        "                            {"
        "                                    userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdLocalStore == null && userIdCookies == null && userIdGlobalCookies != null && userIdFlashCookies == null)"
        "                            {"
        "                                    userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdLocalStore != null && userIdCookies != null && userIdGlobalCookies == null && userIdFlashCookies == null)"
        "                            {"
        "                                    userId = userIdLocalStore;"
        "                            }"
        "                            else if (userIdLocalStore == null && userIdCookies != null && userIdGlobalCookies == null && userIdFlashCookies == null)"
        "                            {"
        "                                    userId = userIdCookies;"
        "                            }"
        "                            else if (userIdLocalStore != null && userIdCookies == null && userIdGlobalCookies == null && userIdFlashCookies == null)"
        "                            {"
        "                                    userId = userIdLocalStore;"
        "                            }"
        "                            else"
        "                            {"
        "                                    userId = ((Math.floor((1 + Math.random()) * 10000000000)).toString() + '-' + (new Date().getTime()).toString());"
        "                            }"
        "                            localStorage.setItem('user_id', userId);"
        "                        }"
        "                        else"
        "                        {"
        "                            if (userIdFlashCookies != null)"
        "                            {"
        "                                userId = userIdFlashCookies;"
        "                            }"
        "                            else if (userIdCookies != null && userIdGlobalCookies != null && userIdFlashCookies == null)"
        "                            {"
        "                                userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdCookies == null && userIdGlobalCookies != null && userIdFlashCookies == null)"
        "                            {"
        "                                userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdCookies != null && userIdGlobalCookies == null && userIdFlashCookies == null)"
        "                            {"
        "                                userId = userIdCookies;"
        "                            }"
        "                            else"
        "                            {"
        "                                userId = ((Math.floor((1 + Math.random()) * 10000000000)).toString() + '-' + (new Date().getTime()).toString());"
        "                            }"
        "                        }"
        "                        set_cookie('%5%', userId, '/','%6%');"
        "                        set_cookie('user_id', userId, '/',location.host);"
        "                        mySwfStore.set('user_id', userId);"
        "                        var iframe = \"<iframe id='\" + iframe_id + \"' src='http://%1%.rg.yottos.com/adshow.fcgi?\" + iframe_query() + \"' width='%3%' height='%4%'  frameborder='0' scrolling='no'></iframe>\";"
        "                        document.getElementById('content').innerHTML = iframe;"
        "                    },"
        "                    onerror: function(){"
        "                        localStorageAvailable = isLocalStorageAvailable();"
        "                        userIdCookies = get_cookie('user_id');"
        "                        userIdGlobalCookies = get_cookie('user_id_global');"
        "                        if (localStorageAvailable)"
        "                        {"
        "                            userIdLocalStore = localStorage.getItem('user_id');"
        "                            if (userIdLocalStore != null && userIdCookies != null && userIdGlobalCookies != null)"
        "                            {"
        "                                if (userIdLocalStore == userIdCookies == userIdGlobalCookies)"
        "                                {"
        "                                    userId = userIdLocalStore;"
        "                                }"
        "                                else if (userIdLocalStore == userIdCookies != userIdGlobalCookies)"
        "                                {"
        "                                    userId = userIdGlobalCookies;"
        "                                }"
        "                                else"
        "                                {"
        "                                    userId = userIdGlobalCookies;"
        "                                }"
        "                            }"
        "                            else if (userIdLocalStore != null && userIdCookies == null && userIdGlobalCookies != null)"
        "                            {"
        "                                    userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdLocalStore == null && userIdCookies != null && userIdGlobalCookies != null)"
        "                            {"
        "                                    userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdLocalStore == null && userIdCookies == null && userIdGlobalCookies != null)"
        "                            {"
        "                                    userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdLocalStore != null && userIdCookies != null && userIdGlobalCookies == null)"
        "                            {"
        "                                    userId = userIdLocalStore;"
        "                            }"
        "                            else if (userIdLocalStore == null && userIdCookies != null && userIdGlobalCookies == null)"
        "                            {"
        "                                    userId = userIdCookies;"
        "                            }"
        "                            else if (userIdLocalStore != null && userIdCookies == null && userIdGlobalCookies == null)"
        "                            {"
        "                                    userId = userIdLocalStore;"
        "                            }"
        "                            else"
        "                            {"
        "                                    userId = ((Math.floor((1 + Math.random()) * 10000000000)).toString() + '-' + (new Date().getTime()).toString());"
        "                            }"
        "                            localStorage.setItem('user_id', userId);"
        "                        }"
        "                        else"
        "                        {"
        "                            if (userIdCookies != null && userIdGlobalCookies != null)"
        "                            {"
        "                                userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdCookies == null && userIdGlobalCookies != null)"
        "                            {"
        "                                userId = userIdGlobalCookies;"
        "                            }"
        "                            else if (userIdCookies != null && userIdGlobalCookies == null)"
        "                            {"
        "                                userId = userIdCookies;"
        "                            }"
        "                            else"
        "                            {"
        "                                userId = ((Math.floor((1 + Math.random()) * 10000000000)).toString() + '-' + (new Date().getTime()).toString());"
        "                            }"
        "                        }"
        "                        set_cookie('%5%', userId, '/','%6%');"
        "                        set_cookie('user_id', userId, '/',location.host);"
        "                        var iframe = \"<iframe id='\" + iframe_id + \"' src='http://%1%.rg.yottos.com/adshow.fcgi?\" + iframe_query() + \"' width='%3%' height='%4%'  frameborder='0' scrolling='no'></iframe>\";"
        "                        document.getElementById('content').innerHTML = iframe;"
        "                    }"
        "                });"
        "            }());"
		"       </script>"
        "    </body>"
        "</html>";
	return true;
}


bool FrameTemplate::init()
{
	return (initFrameTemplate());
}
