#!/usr/bin/python
from pysqlite2 import dbapi2 as sqlite

con = sqlite.connect('key.db')
cur = con.cursor()
cur.execute('CREATE TABLE user_agent_name ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
cur.execute('CREATE TABLE user_agent_ver ( id INTEGER PRIMARY KEY, ver VARCHAR(100), UNIQUE(ver))')
con.commit()
cur.execute('CREATE TABLE user_os ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
cur.execute('CREATE TABLE user_os_ver ( id INTEGER PRIMARY KEY, ver VARCHAR(100), UNIQUE(ver))')
con.commit()
cur.execute('CREATE TABLE os_dist ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
cur.execute('CREATE TABLE os_dist_ver ( id INTEGER PRIMARY KEY, ver VARCHAR(100), UNIQUE(ver))')
con.commit()
cur.execute('CREATE TABLE country ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
cur.execute('CREATE TABLE city ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
cur.execute('CREATE TABLE org ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
cur.execute('CREATE TABLE isp ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
cur.execute('CREATE TABLE informer ( id INTEGER PRIMARY KEY, name VARCHAR(100), UNIQUE(name))')
con.commit()
